# 서버 포트 설정
server:
  port: 8098

# database 연동 설정
#hyeeun
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_solver?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: user_solver
#    password: solver
    username: root
    password: root
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    user:
      name: admin
      password: admin123

  # 메일 정보 설정
  mail:
    host: smtp.naver.com
    port: 465
    username: concatsolver@naver.com

    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

# AWS S3 설정 *********서윤 추가 *********
cloud:
  aws:
    credentials:
      accessKey: AKIAVRUVSZXBMY5MFLM5
      secretKey: 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
    region:
      static: ap-southeast-2
    stack:
      auto: false
    s3:
      bucket: diaperiwinklebucket

  #SNS 로그인
  #    security:
  #      oauth2:
  #        client:
  #          registration:
  #            naver:
  #              client-id: KeB2I8Od5D0f8tGxtz9h
  #              client-secret: cNt49h817S
  #              scope: name, email
  #              client-name: Naver
  #              authorization-grant-type: authorization_code
  #              redirect-uri: http://localhost:8098/login/oauth2/code/naver
  #
  #            google:
  #              client-id: 31911528315-rdtqb9sviamqv3c870fbni1sfqg80957.apps.googleusercontent.com
  #              client-secret: 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
  #              scope: email, profile
  #
  #            kakao:
  #              client-id: b0b82cb476ddfaa6ad5516b1b59d82ac
  #              client-secret: KEw1JTfzGbsKVr11ri2yiiM1ESKuCX3T
  #              scope: account_email, profile_nickname
  #
  #              authorization-grant-type: authorization_code
  #              redirect-uri: http://localhost:8098/login/oauth2/code/kakao
  #              client-name: Kakao
  #              client-authentication-method: client_secret_post
  #
  #            apple:
  #              client-id: your-apple-client-id
  #              client-secret: your-apple-client-secret
  #              scope: email, name
  #              redirect-uri:
  #
  #          provider:
  #            kakao:
  #              authorization-uri: https://kauth.kakao.com/oauth/authorize
  #              token-uri: https://kauth.kakao.com/oauth/token
  #              user-info-uri: https://kapi.kakao.com/v2/user/me
  #              user-name-attribute: id
  #
  #            naver:
  #              authorization-uri: https://nid.naver.com/oauth2.0/authorize
  #              token-uri: https://nid.naver.com/oauth2.0/token
  #              user-info-uri: https://openapi.naver.com/v1/nid/me
  #              user-name-attribute: response
  #
  #            apple:
  #              authorization-uri: https://appleid.apple.com/auth/authorize
  #              token-uri: https://appleid.apple.com/auth/token
  #              user-info-uri: https://appleid.apple.com/auth/userinfo
  
