# 서버 포트 설정
server:
  port: 8098
  #  배포용 포트
#  port: ${PORT:8080}

server.servlet.session.tracking-modes: cookie


# database 연동 설정
#hyeeun
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # AWS RDS URL
    url: jdbc:mysql://solver-db.clc60kwem0qc.ap-northeast-2.rds.amazonaws.com:3306/SOLVER-DB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  #    url: jdbc:mysql://localhost:3306/db_solver?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  #    username: user_solver
  #    password: solver
  #    username: root
  #    password: root
  thymeleaf:
    cache: false
  logging:
    level:
      root: INFO
      concat.SolverWeb: INFO

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    user:
      name: admin
      password: admin123

  # 메일 정보 설정
  mail:
    host: smtp.naver.com
    port: 465
    username: concatsolver@naver.com
    password: concatSolver
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

email:
  from:
    address: concatsolver@naver.com
    name: CONCAT



cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_BUCKET_NAME}



#SNS 로그인
oauth2:
  client:
    registration:
      google:
        client-id: 31911528315-rdtqb9sviamqv3c870fbni1sfqg80957.apps.googleusercontent.com
        client-secret: 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
        redirect-uri: http://localhost:8098/snslogin/oauth2/code/google
        scope: email, profile
        authorization-grant-type: authorization_code
        client-name: Google

      kakao:
        client-id: b0b82cb476ddfaa6ad5516b1b59d82ac
        client-secret: 0OWdNCc7o4uozTJkzSrXLGVbNr5xFQXo
        redirect-uri: http://localhost:8098/snslogin/oauth2/code/kakao
        scope: account_email, profile_nickname
        authorization-grant-type: authorization_code
        client-name: Kakao
        client-authentication-method: client_secret_post

      naver:
        client-id: KeB2I8Od5D0f8tGxtz9h
        client-secret: IbTjnCtNC7
        redirect-uri: http://localhost:8098/snslogin/oauth2/code/naver
        scope: name, email
        authorization-grant-type: authorization_code
        client-name: Naver

  provider:
    kakao:
      authorization-uri: https://kauth.kakao.com/oauth/authorize
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me
      user-name-attribute: id

    naver:
      authorization-uri: https://nid.naver.com/oauth2.0/authorize
      token-uri: https://nid.naver.com/oauth2.0/token
      user-info-uri: https://openapi.naver.com/v1/nid/me
      user-name-attribute: response

    google:
      authorization-uri: https://accounts.google.com/o/oauth2/auth
      token-uri: https://oauth2.googleapis.com/token
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
      user-name-attribute: sub
