# 서버 포트 설정
server:
  port: 8098

# database 연동 설정
#hyeeun
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_solver?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_solver
    password: solver
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  #SNS 로그인
    security:
      oauth2:
        client:
          registration:
            google:
              client-id: 31911528315-rdtqb9sviamqv3c870fbni1sfqg80957.apps.googleusercontent.com
              client-secret: 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
              scope:
                - email
                - profile
              client-name: google
              authorization-grant-type: authorization_code
              redirect-uri: http://localhost:8098/snslogin/oauth2/code/google

            kakao:
              client-id: b0b82cb476ddfaa6ad5516b1b59d82ac
              client-secret: 0OWdNCc7o4uozTJkzSrXLGVbNr5xFQXo
              scope:
                - account_email
                - profile_nickname
              authorization-grant-type: authorization_code
              redirect-uri: http://localhost:8098/snslogin/oauth2/code/kakao
              client-name: kakao
              client-authentication-method: client_secret_post

            naver:
              client-id: KeB2I8Od5D0f8tGxtz9h
              client-secret: IbTjnCtNC7
              scope:
                - name
                - email
              client-name: naver
              authorization-grant-type: authorization_code
              redirect-uri: http://localhost:8098/snslogin/oauth2/code/naver

          provider:
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id

            naver:
              authorization-uri: https://nid.naver.com/oauth2.0/authorize
              token-uri: https://nid.naver.com/oauth2.0/token
              user-info-uri: https://openapi.naver.com/v1/nid/me
              user-name-attribute: response

            google:
              authorization-uri: https://accounts.google.com/o/oauth2/auth
              token-uri: https://oauth2.googleapis.com/token
              user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
              user-name-attribute: sub